if (NOT DEFINED A OR NOT DEFINED B)
    message(FATAL_ERROR "usage: cmake -DA=<exe> -DB=<exe> [-DPREFIX=CASE] [-DMODE=equal|superset] [-DARGS_A=<args>] [-DARGS_B=<args>] -P reach_parity_check.cmake")
endif()

string(REPLACE " " ";" args_a "${ARGS_A}")
string(REPLACE " " ";" args_b "${ARGS_B}")
if (NOT PREFIX)
    set(PREFIX "CASE")
endif()

execute_process(COMMAND ${A} ${args_a} OUTPUT_VARIABLE out_a RESULT_VARIABLE rc_a)
execute_process(COMMAND ${B} ${args_b} OUTPUT_VARIABLE out_b RESULT_VARIABLE rc_b)
if (NOT rc_a EQUAL 0 OR NOT rc_b EQUAL 0)
    message(FATAL_ERROR "harness failure: ${A} rc=${rc_a}, ${B} rc=${rc_b}")
endif()

function(select_lines blob name)
    string(REPLACE "\n" ";" lines "${${blob}}")
    set(picked "")
    foreach (line IN LISTS lines)
        if (line MATCHES "^${PREFIX} ")
            string(APPEND picked "${line}\n")
        endif()
    endforeach()
    string(STRIP "${picked}" picked)
    set(${name} "${picked}" PARENT_SCOPE)
    string(REPLACE "\n" ";" as_list "${picked}")
    list(LENGTH as_list count)
    message(STATUS "${PREFIX} rows from ${${blob}_source_name}: ${count}")
endfunction()

select_lines(out_a rows_a)
select_lines(out_b rows_b)

string(REPLACE "\n" ";" list_a "${rows_a}")
string(REPLACE "\n" ";" list_b "${rows_b}")
list(LENGTH list_a n_a)
list(LENGTH list_b n_b)

if (NOT n_a EQUAL n_b)
    message(FATAL_ERROR "row count mismatch: ${n_a} from ${A} versus ${n_b} from ${B}")
endif()

set(differences 0)
math(EXPR last "${n_a} - 1")
foreach (index RANGE 0 ${last})
    list(GET list_a ${index} line_a)
    list(GET list_b ${index} line_b)
    if (MODE STREQUAL "superset")
        string(REGEX REPLACE "^${PREFIX} (.) +([0-9]+) +([0-9]+) .*" "\\3" count_a "${line_a}")
        string(REGEX REPLACE "^${PREFIX} (.) +([0-9]+) +([0-9]+) .*" "\\3" count_b "${line_b}")
        if (count_a LESS count_b)
            message(SEND_ERROR "shrinkage versus comparator: ${line_b} | ${line_a}")
            math(EXPR differences "${differences} + 1")
        elseif (NOT count_a EQUAL count_b)
            message(STATUS "extra candidates: ${line_a} versus ${line_b}")
        endif()
    elseif (NOT line_a STREQUAL line_b)
        message(SEND_ERROR "row mismatch: ${line_a} | ${line_b}")
        math(EXPR differences "${differences} + 1")
    endif()
endforeach()

if (differences GREATER 0)
    message(FATAL_ERROR "${differences} differing ${PREFIX} rows between ${A} and ${B}")
endif()
if (MODE STREQUAL "superset")
    message(STATUS "${PREFIX}: ${n_a} rows, comparator output is a subset of the new implementation")
else()
    message(STATUS "${PREFIX}: ${n_a} rows identical between ${A} and ${B}")
endif()
